/** Declaration file generated by dts-gen */

export namespace Bot {
    namespace prototype {
        const connector: any;

        const handler: any;

        const sessions: any;

        function createRequestHandler(...args: any[]): void;

        function onEvent(...args: any[]): void;

        function setInitialState(...args: any[]): void;

        function use(...args: any[]): void;

    }

}

export namespace CacheBasedSessionStore {
    namespace prototype {
        function destroy(...args: any[]): void;

        function init(...args: any[]): void;

        function read(...args: any[]): void;

        function write(...args: any[]): void;

    }

}

export namespace ClassifierHandler {
    namespace prototype {
        function build(...args: any[]): void;

        function onIntent(...args: any[]): void;

        function onUnmatched(...args: any[]): void;

    }

}

export namespace ConsoleBot {
    namespace prototype {
        const connector: any;

        const handler: any;

        const sessions: any;

        function createRequestHandler(...args: any[]): void;

        function createRuntime(...args: any[]): void;

        function onEvent(...args: any[]): void;

        function setInitialState(...args: any[]): void;

        function use(...args: any[]): void;

    }

}

export namespace ConsoleConnector {
    namespace prototype {
        const client: any;

        const platform: string;

        function createContext(...args: any[]): void;

        function getUniqueSessionKey(...args: any[]): void;

        function mapRequestToEvents(...args: any[]): void;

        function updateSession(...args: any[]): void;

    }

}

export namespace ConsoleContext {
    namespace prototype {
        const client: any;

        const event: any;

        const isHandled: any;

        const platform: string;

        const session: any;

        const state: {
        };

        function resetState(...args: any[]): void;

        function sendText(...args: any[]): void;

        function setState(...args: any[]): void;

        function typing(...args: any[]): void;

    }

}

export namespace FileSessionStore {
    namespace prototype {
        function destroy(...args: any[]): void;

        function getJFS(...args: any[]): void;

        function init(...args: any[]): void;

        function read(...args: any[]): void;

        function write(...args: any[]): void;

    }

}

export namespace Handler {
    namespace prototype {
        function build(...args: any[]): void;

        function on(...args: any[]): void;

        function onError(...args: any[]): void;

        function onEvent(...args: any[]): void;

        function onMessage(...args: any[]): void;

        function onText(...args: any[]): void;

        function onUnhandled(...args: any[]): void;

    }

}

export namespace LineBot {
    namespace prototype {
        const connector: any;

        const handler: any;

        const sessions: any;

        function createRequestHandler(...args: any[]): void;

        function onEvent(...args: any[]): void;

        function setInitialState(...args: any[]): void;

        function use(...args: any[]): void;

    }

}

export namespace LineConnector {
    namespace prototype {
        const client: any;

        const platform: string;

        function createContext(...args: any[]): void;

        function getUniqueSessionKey(...args: any[]): void;

        function mapRequestToEvents(...args: any[]): void;

        function updateSession(...args: any[]): void;

        function verifySignature(...args: any[]): void;

    }

}

export namespace LineContext {
    namespace prototype {
        const client: any;

        const event: any;

        const isHandled: any;

        const isReplied: any;

        const platform: string;

        const session: any;

        const state: {
        };

        function getLinkedRichMenu(...args: any[]): void;

        function linkRichMenu(...args: any[]): void;

        function pushAudio(...args: any[]): void;

        function pushButtonTemplate(...args: any[]): void;

        function pushCarouselTemplate(...args: any[]): void;

        function pushConfirmTemplate(...args: any[]): void;

        function pushImage(...args: any[]): void;

        function pushImageCarouselTemplate(...args: any[]): void;

        function pushImagemap(...args: any[]): void;

        function pushLocation(...args: any[]): void;

        function pushSticker(...args: any[]): void;

        function pushText(...args: any[]): void;

        function pushVideo(...args: any[]): void;

        function replyAudio(...args: any[]): void;

        function replyButtonTemplate(...args: any[]): void;

        function replyCarouselTemplate(...args: any[]): void;

        function replyConfirmTemplate(...args: any[]): void;

        function replyImage(...args: any[]): void;

        function replyImageCarouselTemplate(...args: any[]): void;

        function replyImagemap(...args: any[]): void;

        function replyLocation(...args: any[]): void;

        function replySticker(...args: any[]): void;

        function replyText(...args: any[]): void;

        function replyVideo(...args: any[]): void;

        function resetState(...args: any[]): void;

        function sendAudio(...args: any[]): void;

        function sendButtonTemplate(...args: any[]): void;

        function sendCarouselTemplate(...args: any[]): void;

        function sendConfirmTemplate(...args: any[]): void;

        function sendImage(...args: any[]): void;

        function sendImageCarouselTemplate(...args: any[]): void;

        function sendImagemap(...args: any[]): void;

        function sendLocation(...args: any[]): void;

        function sendSticker(...args: any[]): void;

        function sendText(...args: any[]): void;

        function sendVideo(...args: any[]): void;

        function setState(...args: any[]): void;

        function typing(...args: any[]): void;

        function unlinkRichMenu(...args: any[]): void;

    }

}

export namespace LineHandler {
    namespace prototype {
        function build(...args: any[]): void;

        function on(...args: any[]): void;

        function onBeacon(...args: any[]): void;

        function onError(...args: any[]): void;

        function onEvent(...args: any[]): void;

        function onFollow(...args: any[]): void;

        function onJoin(...args: any[]): void;

        function onLeave(...args: any[]): void;

        function onMessage(...args: any[]): void;

        function onPayload(...args: any[]): void;

        function onPostback(...args: any[]): void;

        function onText(...args: any[]): void;

        function onUnfollow(...args: any[]): void;

        function onUnhandled(...args: any[]): void;

    }

}

export namespace MemoryCacheStore {
    namespace prototype {
        function flush(...args: any[]): void;

        function forget(...args: any[]): void;

        function get(...args: any[]): void;

        function getPrefix(...args: any[]): void;

        function put(...args: any[]): void;

    }

}

export namespace MemorySessionStore {
    namespace prototype {
        function destroy(...args: any[]): void;

        function init(...args: any[]): void;

        function read(...args: any[]): void;

        function write(...args: any[]): void;

    }

}

export namespace MessengerBot {
    namespace prototype {
        const connector: any;

        const handler: any;

        const sessions: any;

        function createRequestHandler(...args: any[]): void;

        function onEvent(...args: any[]): void;

        function setInitialState(...args: any[]): void;

        function use(...args: any[]): void;

    }

}

export namespace MessengerConnector {
    namespace prototype {
        const client: any;

        const platform: string;

        function createContext(...args: any[]): void;

        function getUniqueSessionKey(...args: any[]): void;

        function mapRequestToEvents(...args: any[]): void;

        function updateSession(...args: any[]): void;

        function verifySignature(...args: any[]): void;

    }

}

export namespace MessengerContext {
    namespace prototype {
        const client: any;

        const event: any;

        const isHandled: any;

        const platform: string;

        const session: any;

        const state: {
        };

        function associateLabel(...args: any[]): void;

        function dissociateLabel(...args: any[]): void;

        function getAssociatedLabels(...args: any[]): void;

        function markSeen(...args: any[]): void;

        function passThreadControl(...args: any[]): void;

        function passThreadControlToPageInbox(...args: any[]): void;

        function resetState(...args: any[]): void;

        function sendAirlineBoardingPassTemplate(...args: any[]): void;

        function sendAirlineCheckinTemplate(...args: any[]): void;

        function sendAirlineFlightUpdateTemplate(...args: any[]): void;

        function sendAirlineItineraryTemplate(...args: any[]): void;

        function sendAttachment(...args: any[]): void;

        function sendAudio(...args: any[]): void;

        function sendButtonTemplate(...args: any[]): void;

        function sendFile(...args: any[]): void;

        function sendGenericTemplate(...args: any[]): void;

        function sendImage(...args: any[]): void;

        function sendListTemplate(...args: any[]): void;

        function sendMediaTemplate(...args: any[]): void;

        function sendMessage(...args: any[]): void;

        function sendOpenGraphTemplate(...args: any[]): void;

        function sendQuickReplies(...args: any[]): void;

        function sendReceiptTemplate(...args: any[]): void;

        function sendTemplate(...args: any[]): void;

        function sendText(...args: any[]): void;

        function sendVideo(...args: any[]): void;

        function setState(...args: any[]): void;

        function takeThreadControl(...args: any[]): void;

        function typing(...args: any[]): void;

        function typingOff(...args: any[]): void;

        function typingOn(...args: any[]): void;

    }

}

export namespace MessengerHandler {
    namespace prototype {
        function build(...args: any[]): void;

        function on(...args: any[]): void;

        function onAudio(...args: any[]): void;

        function onCheckoutUpdate(...args: any[]): void;

        function onDelivery(...args: any[]): void;

        function onEcho(...args: any[]): void;

        function onError(...args: any[]): void;

        function onEvent(...args: any[]): void;

        function onFallback(...args: any[]): void;

        function onFile(...args: any[]): void;

        function onImage(...args: any[]): void;

        function onLocation(...args: any[]): void;

        function onMessage(...args: any[]): void;

        function onOptin(...args: any[]): void;

        function onPayload(...args: any[]): void;

        function onPayment(...args: any[]): void;

        function onPostback(...args: any[]): void;

        function onPreCheckout(...args: any[]): void;

        function onQuickReply(...args: any[]): void;

        function onRead(...args: any[]): void;

        function onText(...args: any[]): void;

        function onUnhandled(...args: any[]): void;

        function onVideo(...args: any[]): void;

    }

}

export namespace MongoSessionStore {
    namespace prototype {
        function destroy(...args: any[]): void;

        function init(...args: any[]): void;

        function read(...args: any[]): void;

        function write(...args: any[]): void;

    }

}

export namespace RedisCacheStore {
    namespace prototype {
        function flush(...args: any[]): void;

        function forget(...args: any[]): void;

        function get(...args: any[]): void;

        function getPrefix(...args: any[]): void;

        function getRedis(...args: any[]): void;

        function put(...args: any[]): void;

        function setPrefix(...args: any[]): void;

    }

}

export namespace RedisSessionStore {
    namespace prototype {
        function destroy(...args: any[]): void;

        function init(...args: any[]): void;

        function read(...args: any[]): void;

        function write(...args: any[]): void;

    }

}

export namespace SlackBot {
    namespace prototype {
        const connector: any;

        const handler: any;

        const sessions: any;

        function createRequestHandler(...args: any[]): void;

        function onEvent(...args: any[]): void;

        function setInitialState(...args: any[]): void;

        function use(...args: any[]): void;

    }

}

export namespace SlackConnector {
    namespace prototype {
        const client: any;

        const platform: string;

        function createContext(...args: any[]): void;

        function getUniqueSessionKey(...args: any[]): void;

        function mapRequestToEvents(...args: any[]): void;

        function updateSession(...args: any[]): void;

    }

}

export namespace SlackContext {
    namespace prototype {
        const client: any;

        const event: any;

        const isHandled: any;

        const platform: string;

        const session: any;

        const state: {
        };

        function postMessage(...args: any[]): void;

        function resetState(...args: any[]): void;

        function sendText(...args: any[]): void;

        function setState(...args: any[]): void;

        function typing(...args: any[]): void;

    }

}

export namespace SlackHandler {
    namespace prototype {
        function build(...args: any[]): void;

        function on(...args: any[]): void;

        function onError(...args: any[]): void;

        function onEvent(...args: any[]): void;

        function onMessage(...args: any[]): void;

        function onText(...args: any[]): void;

        function onUnhandled(...args: any[]): void;

    }

}

export namespace TelegramBot {
    namespace prototype {
        const connector: any;

        const handler: any;

        const sessions: any;

        function createRequestHandler(...args: any[]): void;

        function onEvent(...args: any[]): void;

        function setInitialState(...args: any[]): void;

        function use(...args: any[]): void;

    }

}

export namespace TelegramConnector {
    namespace prototype {
        const client: any;

        const platform: string;

        function createContext(...args: any[]): void;

        function getUniqueSessionKey(...args: any[]): void;

        function mapRequestToEvents(...args: any[]): void;

        function updateSession(...args: any[]): void;

    }

}

export namespace TelegramContext {
    namespace prototype {
        const client: any;

        const event: any;

        const isHandled: any;

        const platform: string;

        const session: any;

        const state: {
        };

        function resetState(...args: any[]): void;

        function sendAudio(...args: any[]): void;

        function sendChatAction(...args: any[]): void;

        function sendContact(...args: any[]): void;

        function sendDocument(...args: any[]): void;

        function sendLocation(...args: any[]): void;

        function sendMessage(...args: any[]): void;

        function sendPhoto(...args: any[]): void;

        function sendSticker(...args: any[]): void;

        function sendText(...args: any[]): void;

        function sendVenue(...args: any[]): void;

        function sendVideo(...args: any[]): void;

        function sendVideoNote(...args: any[]): void;

        function sendVoice(...args: any[]): void;

        function setState(...args: any[]): void;

        function typing(...args: any[]): void;

    }

}

export namespace TelegramHandler {
    namespace prototype {
        function build(...args: any[]): void;

        function on(...args: any[]): void;

        function onAudio(...args: any[]): void;

        function onCallbackQuery(...args: any[]): void;

        function onContact(...args: any[]): void;

        function onDocument(...args: any[]): void;

        function onError(...args: any[]): void;

        function onEvent(...args: any[]): void;

        function onGame(...args: any[]): void;

        function onLocation(...args: any[]): void;

        function onMessage(...args: any[]): void;

        function onPayload(...args: any[]): void;

        function onPhoto(...args: any[]): void;

        function onSticker(...args: any[]): void;

        function onText(...args: any[]): void;

        function onUnhandled(...args: any[]): void;

        function onVenue(...args: any[]): void;

        function onVideo(...args: any[]): void;

        function onVideoNote(...args: any[]): void;

        function onVoice(...args: any[]): void;

    }

}

